echo "User $USER in directory $PWD."
echo "-----------------------------"
echo "---List of basic commands---"
echo "---The current user\'s home directory : $HOME."
echo "---The current user : $USER. "
echo "---A colon-separated list of directories in which the shell looks for commands : $PATH."
echo "---The current working directory : $PWD."
echo "---Random integer between 0 and 32767 : $RANDOM."
echo "---The numeric, real user ID of the current user : $UID."
echo "---The primary prompt string : $PS1."
echo "---The secondary prompt string : $PS2."  
echo "-----------------------------"
